sudo: required

language: go

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t mbialon/concourse-docker-manifest-resource .

after_success:
  - docker push mbialon/concourse-docker-manifest-resource